---
title: "Draft for sequencing data download"
author: "Morten Dall"
output: html_document
---

```{r setup, include=FALSE}
library(GEOquery)
library(tidyverse)
library(fs)
library(vroom)
library(Biobase)
library(here)
library(magrittr)
library(data.table)
library(clusterProfiler)
library(org.Hs.eg.db)
library(edgeR)
library(openxlsx)

```




```{r}

goTables <- vector(mode = "list", length = 4)
for (i in 1:4) {
  goTables[[i]]<- goTest[[i]]@result
}



plot_test <- dotplot(goResults)
plot_test
goResults <- setReadable(goResults, OrgDb = org.Hs.eg.db, keyType="ENTREZID")
write.xlsx(goResults, file = here("data/NASH_NAFLD_GOterms.xlsx"), asTable = TRUE)
cnet <- cnetplot(goResults)


printGOterms(goTest) 

dir.create(here("data/figures"), showWarnings = F)

dotplot <- dotplot(goTest[[1]], )

ggsave(dotplot, filename = paste("myplot","1",".png"))

printGOterms(goResults)

 goSheets<- vector(mode = "list", length = length(goTest))
  for (i in 1:length(goSheets)){
    goSheets[[i]] <- goTest[[i]]@result
    names(goSheets)[i]<-names(goTest)[i]
  }
  write.xlsx(goSheets, file = here("data/NASH_NAFLD_GOterms.xlsx"), asTable = TRUE)

```


```{r}
#' Title
#'
#' @param RNAlist 
#' @param goList 
#'
#' @return
#' @export
#'
#' @examples
NAD_terms_extractor <- function(RNAlist, goList){
  Selected_candidates <- c("NAMPT", 
                         "NMNAT1", 
                         "NMNAT2", 
                         "NMNAT3", 
                         "NMRK1", 
                         "NMRK2", 
                         "NADSYN1", 
                         "NADSYN", 
                         "TDO2", 
                         "IDO", 
                         "NAPRT", 
                         "SIRT1", 
                         "SIRT3", 
                         "PARP1", 
                         "CD38", 
                         "NNMT", 
                         "NADK", 
                         "HADH", 
                         "KMO",
                         "AFMID")
  NAD_tables <- vector(mode = "list", length = 2 * length(goList))
  for (i in length(goList)) {
    NAD_tables[[i]] <- goList[[i]]@result %>%
      filter(str_detect(Description, "NAD"))
    names(NAD_tables[i]) <-
      paste("NAD_terms", names(goList[i]), sep = "")
    NAD_tables[[i + length(goList)]] <- RNAlist[[i]] %>%
      filter(SYMBOL %in% Selected_candidates)
    names(NAD_tables[i+length(RNAlist)]) <-
      paste("NAD_genes", names(RNAlist[i]), sep = "")
  }
  return(NAD_tables)
 
}

NAD_test <- NAD_terms_extractor(results,goResult)

View(NAD_test)

  
goTerms <- goResults@result %>%
  filter(ID == "GO:0009435"	)
View(goTerms)
NADGenes <- goTerms$geneID
NADGenes_list <- unlist(strsplit(NADGenes, "/"))

significant_NAD_terms <- results %>%
  filter(rownames(results[[3]]) %in% NADGenes_list)
View(significant_NAD_terms)
View(results)

NAD_screen <- results[[3]] %>%
  

ggplot(NAD_screen, aes(x = logFC, y = -log10(FDR))) +
  geom_point()

```

